bot_name: crypto-invest-bot

actions:
  - name: "Buy ETH"
    type: order
    pair: ETHUSD
    side: buy
    amount: 20.00
    schedule: "8 15 * * *"  # every day at 10:08 EST

  - name: "Stake all ETH"
    type: earn
    asset: ETH
    strategy: restaked
    amount: null
    schedule: "9 15 * * *"  # every day at 10:09 EST

  - name: "Buy SOL"
    type: order
    pair: SOLUSD
    side: buy
    amount: 20.00
    schedule: "3 0 * * *"  # every day at 19:03 EST

  - name: "Stake all SOL"
    type: earn
    asset: SOL
    strategy: bonded
    amount: null
    schedule: "4 0 * * *"  # every day at 19:04 EST
