bot_name: crypto-invest-bot

actions:
  - name: "Buy ETH"
    type: order
    pair: XETHZUSD
    side: buy
    amount: 10.00
    schedule: "59 4 * * *"  # every day at 23:59 ET

  - name: "Stake all ETH"
    type: earn
    asset: XETH
    strategy: restaking
    amount: null
    schedule: "0 5 * * *"  # every day at 00:00 ET

  - name: "Buy SOL"
    type: order
    pair: SOLUSD
    side: buy
    amount: 10.00
    schedule: "59 4 * * *"  # every day at 23:59 ET

  - name: "Stake all SOL"
    type: earn
    asset: SOL
    strategy: restaking
    amount: null
    schedule: "0 5 * * *"  # every day at 00:00 ET
